### ISSUE TITLE
Adding Sub Categories

### ISSUE THREAD

**Issue by KugaTog** [sant0ro/chocolatey#119]
This isn't really an issue but a question...
How do I add another sub directory?

![image](https://cloud.githubusercontent.com/assets/26791733/24578639/966176a0-16a1-11e7-8bef-c7c3bfce1e61.png)

As in if I wanted to add another page beside what's new and messaging.

**Comment by s150217754** [comment]
This is presently not possible. It will be made possible through the Chocolatey Plugin System in the near future. 

If you have some basic coding skills, you may modify the scripts.js to fit your need. However, do note that whatever errors you do encounter due to your modification won't be supported by us.

**Comment by sant0ro** [comment]
Hello, exactly what @s150217754 said. The Plugin system will be coded in this month.

A new branch called plugin-system will be created in order to develop it, since it need to be good coded, and easy to be used.
