### ISSUE TITLE
Captcha serverside

### ISSUE THREAD

**Issue by dominicusdev** [sant0ro/chocolatey#161]
Captcha is not validated server-sided

**Comment by sant0ro** [comment]
I know that, but I really don't think that it's so easy break the client-side Captcha.

And is still a Habbo Retro. We don't really need do this.

But if preferable I can do it.

**Comment by dominicusdev** [comment]
It's annoying, because it's just removing the check it does to know whether it's filled or not.

**Comment by sant0ro** [comment]
The AngularJS does the check if is filled or not.

You cannot submit without checking.

**Comment by sant0ro** [comment]
Closing due no answer.

**Comment by dominicusdev** [comment]
You can code a bot to remove this check, hence a serverside check

**Comment by sant0ro** [comment]
Google ReCaptcha it's bot proof. Anyways, Angular does the whole communication.

What actually you can do is a XSS attack if the CORS is misconfigured.

In this case, since server check doesn't exists you can actually create an account from anywhere just doing a POST request.

So, agreeing with you, server side check is necessary.
