### ISSUE TITLE
Test if Photos are still working correctly.

### ISSUE THREAD

**Issue by sant0ro** [sant0ro/chocolatey#163]
Since a minor change happened to the `str_replace` method inside the `Photo` class, some users reporting that the picture doesn't load because of extra http//, can you check if the image is appearing or not? 

In Resume.: Check if the Photo Url Fixer on the Photo class is still working.

**Comment by s150217754** [comment]
The Picture doesn't load because they are probably on HTTPS and Arcturus.wf site have not yet renewed their SSL.

It works fine on HTTP (non-secured). See image:

![photo1](https://cloud.githubusercontent.com/assets/25793165/24971904/22455b3e-1fec-11e7-9be0-25968d9e06f4.png)
![photo2](https://cloud.githubusercontent.com/assets/25793165/24971905/22f9a080-1fec-11e7-984a-10c198cea401.png)


Anyway, a temporary solution is to code a small script using php readfile or file_get_contents.

I personally coded a readfile script so that the camera image would display _in client_ on HTTPS since Habbo.swf will reject mixed content between HTTP and HTTPS.

**Comment by sant0ro** [comment]
In resume: The code isn't working and need patches?

**Comment by s150217754** [comment]
Problem lies on Arcturus not having SSL. 

But We can easily patch by fetching the unsecured images using readfile or file_get_contents similar to the YouTube imager.

**Comment by sant0ro** [comment]
I see, so the solution it's creating a code that redirect's into http.

Okay will do it.

**Comment by sant0ro** [comment]
I think I cannot do it.

Since this is an Arcturus.wf related Issue, Isn't good do "hacking" in URI's.

I will talk to Wesley to fix their SSL.

**Comment by s150217754** [comment]
@sant0ro It'll be much better if it's fixed on Arcturus.wf

However, You might want to see this: https://bitbucket.org/Wesley12312/arcturus/issues/355/arcturuswf-ssl-support

Wesley mentioned the possibility of the end-user to create a imageproxy.
