### ISSUE TITLE
Error: MethodNotAllowedHttpException in RoutesRequests.php line 596:

### ISSUE THREAD

**Issue by AlexJey** [sant0ro/chocolatey#209]
Hi,
i have an error on localhost/api/public/registration/new!
in RoutesRequests.php line 596
at Application->handleDispatcherResponse(array(2, array('POST'))) in RoutesRequests.php line 532
at Application->Laravel\Lumen\Concerns\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
at Pipeline->Laravel\Lumen\Routing\{closure}(object(Request)) in MaintenanceModeMiddleware.php line 49
at MaintenanceModeMiddleware->handle(object(Request), object(Closure)) in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Laravel\Lumen\Routing\{closure}(object(Request)) in Pipeline.php line 102
at Pipeline->then(object(Closure)) in RoutesRequests.php line 778
at Application->sendThroughPipeline(array('Rdehnhardt\\MaintenanceMode\\Http\\Middleware\\MaintenanceModeMiddleware'), object(Closure)) in RoutesRequests.php line 534
at Application->dispatch(null) in RoutesRequests.php line 475
at Application->run() in index.php line 26
Please, help me to resolve!

**Comment by sant0ro** [comment]
Hi @AlexJey!

Thanks for reporting an Issue to the **Chocolatey Repository**.

We're glad that you're using our software. I need to remember that **this** message was generated automatically.

In order to **gracefully** report your Issue, please we recommend the followance of those requirements:

Here's what to do: if you need help:

* Inform a complete message of your problem, and what's happening.
* Attach your **lumen.log** if it exists.
* Attach images of the reported bugs/glitches.
* Attach also Information about Operational System, Web Server, PHP Versiom, and other infos.
* Explain what you tried and how tried.

Recommendations About your recently opened Issue?
--------------------------------

We really recommend using [Lightshot](https://app.prntscr.com/pt-br/download.html) to take your screenshot. It allows marks, annotations and more.

If you bug it's about a feature from **Chocolatey** or glitch, we **trully** recommend taking a **HAR File**. You can attach a [HAR File following this procedure](https://support.cloudflare.com/hc/en-us/articles/203118044-How-do-I-generate-a-HAR-file-).

A **HAR** file it's a complete log of the network requests of a specific page.

Also we recommend specify some Informations about your **OS** like.:

* Operational System
* Which Web Server are you using (like XAMPP)
* Which version of Web Server Using (eg.: 1.7.3)
* Which version of php & mysql & apache using. (Specify if is possible)
* How much RAM does you have?

Are you creating a Feature Request?
------------------------------

About Feature requests, we recommend you specify completely about what your **Feature Request** is. Tag the type of change that you want to be added.

Changes need to be specified, and you need specify why and what you want to be changed/added.

Be creatively and try explain in the best manner as possible.

Tag the Issue on the Title
-------------------------------

Tagging your Issue will be the best thing you can do for us. We separate issues by tags, and we can work more quickly by knowing from what is the Issue related.

**Those are the available tags:**

* Security
* Angular
* Feature Request
* Server Error
* HabboWEB Glitch
* Translation Mistake
* CSS Mistake/Glitch
* Feature not Working
* Help Wanted
* Can't Install
* Urgent Issue
* Game Bug
* Migration Bug
* Upgrading Bug

**Remember to tag on the title of the Issue [_Issue Type_]**

I updated my Issue.. And now?
---------------------------

You wait.

We have **ful-jobs** and a **life**, we will receive updates by e-mail and soon as possible update your **Issue** by tagging it correctly, assigning to our team and **obviously** answering it.

Then we will support you and help you in what we can.

Also if you Issue it's out of the **params** we will not answer it, or answer it **asking to you fix and correct the main message**

If you dom't know how to use GitHub correctly, check [this](https://guides.github.com/features/issues/) tutorial.

Further information
-------------------

* This **BOT** was originally created by @ajdlinux and @daxtens.
* Edited by @sant0ro for own purposes.
* Contributors of Chocolatey @BobyTS and @s150217754

**Comment by AlexJey** [comment]
You have skype?

**Comment by sant0ro** [comment]
Hello @AlexJey no need of it. All Issues we clearly solve here.

I will be analyzing your Issue now. But if possible update your Issue with some more information.

Thanks!

**Comment by sant0ro** [comment]
If possible attach the whole lumen.log

**Comment by AlexJey** [comment]
Ok

**Comment by AlexJey** [comment]
Lumen.log : http://www.filedropper.com/lumen

**Comment by sant0ro** [comment]
You can attach it directly on this Issue. But nvm. Downloading it.

**Comment by sant0ro** [comment]
Your log it's so much big. Clear it and try again create your account.

Does you followed the tutorial? Did 'php artisan migrate' ?

**Comment by AlexJey** [comment]
[lumen.zip](https://github.com/sant0ro/chocolatey/files/955499/lumen.zip)

**Comment by AlexJey** [comment]
Okay?

**Comment by sant0ro** [comment]
Okay, I'm glad that you learned. But doesn't need zip it.

Can you delete the `lumne.log` file and try to register again.

Your Lumen.log has too much errors, need see what exactly is happening.

**Comment by AlexJey** [comment]
yes

**Comment by AlexJey** [comment]
ok

**Comment by AlexJey** [comment]
Not resolved

**Comment by AlexJey** [comment]
[2017-04-25 16:14:38] lumen.ERROR: Swift_TransportException: Expected response code 250 but got code "530", with message "530 5.7.0 Must issue a STARTTLS command first
" in C:\inetpub\happy\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php:383
Stack trace:
#0 C:\inetpub\happy\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php(281): Swift_Transport_AbstractSmtpTransport->_assertResponseCode('530 5.7.0 Must ...', Array)
#1 C:\inetpub\happy\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\EsmtpTransport.php(270): Swift_Transport_AbstractSmtpTransport->executeCommand('MAIL FROM:<happ...', Array, Array)
#2 C:\inetpub\happy\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\EsmtpTransport.php(346): Swift_Transport_EsmtpTransport->executeCommand('MAIL FROM:<happ...', Array)
#3 C:\inetpub\happy\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php(416): Swift_Transport_EsmtpTransport->_doMailFromCommand('happy.europe@ou...')
#4 C:\inetpub\happy\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php(443): Swift_Transport_AbstractSmtpTransport->_doMailTransaction(Object(Swift_Message), 'happy.europe@ou...', Array, Array)
#5 C:\inetpub\happy\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php(176): Swift_Transport_AbstractSmtpTransport->_sendTo(Object(Swift_Message), 'happy.europe@ou...', Array, Array)
#6 C:\inetpub\happy\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mailer.php(85): Swift_Transport_AbstractSmtpTransport->send(Object(Swift_Message), Array)
#7 C:\inetpub\happy\vendor\illuminate\mail\Mailer.php(423): Swift_Mailer->send(Object(Swift_Message), Array)
#8 C:\inetpub\happy\vendor\illuminate\mail\Mailer.php(208): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#9 C:\inetpub\happy\vendor\illuminate\support\Facades\Facade.php(221): Illuminate\Mail\Mailer->send('habbo-web-mail....', Array, Object(Closure))
#10 C:\inetpub\happy\app\Http\Controllers\MailController.php(30): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#11 C:\inetpub\happy\app\Http\Controllers\AccountController.php(216): App\Http\Controllers\MailController->send(Array)
#12 C:\inetpub\happy\app\Http\Controllers\LoginController.php(83): App\Http\Controllers\AccountController->createUser(Object(Illuminate\Http\Request), Array, true)
#13 [internal function]: App\Http\Controllers\LoginController->register(Object(Illuminate\Http\Request))
#14 C:\inetpub\happy\vendor\illuminate\container\BoundMethod.php(28): call_user_func_array(Array, Array)
#15 C:\inetpub\happy\vendor\illuminate\support\helpers.php(912): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#16 C:\inetpub\happy\vendor\illuminate\container\BoundMethod.php(86): value(Object(Closure))
#17 C:\inetpub\happy\vendor\illuminate\container\BoundMethod.php(30): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#18 C:\inetpub\happy\vendor\illuminate\container\Container.php(524): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#19 C:\inetpub\happy\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(741): Illuminate\Container\Container->call(Array, Array)
#20 C:\inetpub\happy\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(707): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#21 C:\inetpub\happy\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(681): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\LoginController), 'register', Array)
#22 C:\inetpub\happy\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(643): Laravel\Lumen\Application->callControllerAction(Array)
#23 C:\inetpub\happy\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(623): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#24 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#25 C:\inetpub\happy\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 C:\inetpub\happy\app\Http\Middleware\Maintenance.php(25): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#27 C:\inetpub\happy\vendor\illuminate\pipeline\Pipeline.php(148): App\Http\Middleware\Maintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 C:\inetpub\happy\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 C:\inetpub\happy\vendor\illuminate\pipeline\Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#31 C:\inetpub\happy\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#32 C:\inetpub\happy\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(624): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#33 C:\inetpub\happy\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(528): Laravel\Lumen\Application->handleFoundRoute(Array)
#34 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#35 C:\inetpub\happy\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#36 C:\inetpub\happy\vendor\rdehnhardt\lumen-maintenance-mode\src\Http\Middleware\MaintenanceModeMiddleware.php(49): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#37 C:\inetpub\happy\vendor\illuminate\pipeline\Pipeline.php(148): Rdehnhardt\MaintenanceMode\Http\Middleware\MaintenanceModeMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 C:\inetpub\happy\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#40 C:\inetpub\happy\vendor\illuminate\pipeline\Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#41 C:\inetpub\happy\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#42 C:\inetpub\happy\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(534): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#43 C:\inetpub\happy\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(475): Laravel\Lumen\Application->dispatch(NULL)
#44 C:\inetpub\happy\index.php(26): Laravel\Lumen\Application->run()
#45 {main}

**Comment by sant0ro** [comment]
Okay, I think you're not using last version of `chocolatey`

this error is really simple, go on your `config/mail.php` and disable mailing system by putting 'enable => false', something like that.

**Comment by AlexJey** [comment]
View on this, http://happyhotel.eu

**Comment by AlexJey** [comment]
I have translate 100 % ITALIAN Language for chocolatey

**Comment by AlexJey** [comment]
And i use the plus emulator

**Comment by sant0ro** [comment]
Yes I see, but I see but you need download latest version of Chocolatey.

Available here: https://github.com/sant0ro/chocolatey/releases/tag/3.000B

And change to `'enable' => false` on `config/mail.php`

**Comment by AlexJey** [comment]
I not use arcuturs emulator, i use the plus emulator

**Comment by sant0ro** [comment]
I see, but Chocolatey isn't compatible with Plus. I really don't know how you got it working.

Sadly I cannot give support for Plus Emulator. Many things can happen badly.

**Comment by AlexJey** [comment]
And i not use the linux, i use the IIS

**Comment by AlexJey** [comment]
Ehehehehe, you say not compatibility on IIS and i compatibility on iis  👍

**Comment by sant0ro** [comment]
I will ask to @BobyTS give you support.

**Comment by AlexJey** [comment]
You post the language ok?

**Comment by AlexJey** [comment]
Please add the language italian, i have created for chocolaty

**Comment by AlexJey** [comment]
For me, is not a problem Chocolatey cms, is for arcuturs and i use for plus emulator 👍

**Comment by sant0ro** [comment]
Okay @AlexJey I'll ask you to Download Arcturus 1.6.0, import database, and follow all steps to Install Chocolatey.

French & Italian & Portuguese Language will be added by @BobyTS

**Comment by AlexJey** [comment]
I have translate the 100 %

**Comment by sant0ro** [comment]
I'm leaving this Issue up to @BobyTS .

I'll also ask you to reduce the amount of answers on this Issue. This isn't a conversation.

Keep multiple comments in a single comment. This is better for readability.

Thanks :)

**Comment by AlexJey** [comment]
For the conversation? , find?

**Comment by BobyTS** [comment]
Hello @AlexJey 
I can support your translation to implement it on the project if you wish.

Can you provide me with .rar/.zip pages you translated?
Alternatively you can setup a fork to create a pull request.

**Comment by sant0ro** [comment]
@BobyTS I think @AlexJey is newbie. But he can give a try.

Anyways @BobyTS I see that his hotel has a Cookie Banner on his Chocolatey version. This Cookie banner never appeared for me before.

**Comment by BobyTS** [comment]
I have the cookie banner also on my site.

**Comment by s150217754** [comment]
@sant0ro @BobyTS If I recall correctly, HabboWEB will show the Cookie Banner if the hotel region is set within the EU. This is to comply with the relevant law.
