### ISSUE TITLE
Restart - Choose style & room.

### ISSUE THREAD

**Issue by Iluminatos** [sant0ro/chocolatey#213]
Hi. 

When logging in to my hotel i get to choose my **Style & choose room** for the first time.

But.. when i've restart the hotel i get the rights to choose style, name, room again?
 Like the room, name, style function restarts when the server restarts (Does not save)? 

https://gyazo.com/2a376c81d67a7742cfdcab6296142fa8
My localhost/community/photos randomly doesnt exist anymore?

**Comment by sant0ro** [comment]
Hi @Iluminatos!

Thanks for reporting an Issue to the **Chocolatey Repository**.

We're glad that you're using our software. I need to remember that **this** message was generated automatically.

In order to **gracefully** report your Issue, please we recommend the followance of those requirements:

Here's what to do: if you need help:

* Inform a complete message of your problem, and what's happening.
* Attach your **lumen.log** if it exists.
* Attach images of the reported bugs/glitches.
* Attach also Information about Operational System, Web Server, PHP Versiom, and other infos.
* Explain what you tried and how tried.

Recommendations About your recently opened Issue?
--------------------------------

We really recommend using [Lightshot](https://app.prntscr.com/pt-br/download.html) to take your screenshot. It allows marks, annotations and more.

If you bug it's about a feature from **Chocolatey** or glitch, we **trully** recommend taking a **HAR File**. You can attach a [HAR File following this procedure](https://support.cloudflare.com/hc/en-us/articles/203118044-How-do-I-generate-a-HAR-file-).

A **HAR** file it's a complete log of the network requests of a specific page.

Also we recommend specify some Informations about your **OS** like.:

* Operational System
* Which Web Server are you using (like XAMPP)
* Which version of Web Server Using (eg.: 1.7.3)
* Which version of php & mysql & apache using. (Specify if is possible)
* How much RAM does you have?

Are you creating a Feature Request?
------------------------------

About Feature requests, we recommend you specify completely about what your **Feature Request** is. Tag the type of change that you want to be added.

Changes need to be specified, and you need specify why and what you want to be changed/added.

Be creatively and try explain in the best manner as possible.

Tag the Issue on the Title
-------------------------------

Tagging your Issue will be the best thing you can do for us. We separate issues by tags, and we can work more quickly by knowing from what is the Issue related.

**Those are the available tags:**

* Security
* Angular
* Feature Request
* Server Error
* HabboWEB Glitch
* Translation Mistake
* CSS Mistake/Glitch
* Feature not Working
* Help Wanted
* Can't Install
* Urgent Issue
* Game Bug
* Migration Bug
* Upgrading Bug

**Remember to tag on the title of the Issue [_Issue Type_]**

I updated my Issue.. And now?
---------------------------

You wait.

We have **ful-jobs** and a **life**, we will receive updates by e-mail and soon as possible update your **Issue** by tagging it correctly, assigning to our team and **obviously** answering it.

Then we will support you and help you in what we can.

Also if you Issue it's out of the **params** we will not answer it, or answer it **asking to you fix and correct the main message**

If you dom't know how to use GitHub correctly, check [this](https://guides.github.com/features/issues/) tutorial.

Further information
-------------------

* This **BOT** was originally created by @ajdlinux and @daxtens.
* Edited by @sant0ro for own purposes.
* Contributors of Chocolatey @BobyTS and @s150217754

**Comment by Iluminatos** [comment]
I do not understand this. Dont know whats wrong with my ticket, thanks.

**Comment by Iluminatos** [comment]
https://gyazo.com/2a376c81d67a7742cfdcab6296142fa8
My localhost/community/photos randomly doesnt exist anymore?

**Comment by Iluminatos** [comment]
@sant0ro

**Comment by sant0ro** [comment]
Wait, @Iluminatos I'm busy now. I'll ask to someone else help you.

**Comment by Iluminatos** [comment]
Thanks @sant0ro.

**Comment by Iluminatos** [comment]
Thanks @sant0ro.

**Comment by BobyTS** [comment]
Hello @Iluminatos 
Please give us your **lumen.log**

**Comment by Iluminatos** [comment]
Where is **lumen.log** located?

**Comment by BobyTS** [comment]
*your chocolatey installation*/storage/logs

**Comment by Iluminatos** [comment]
https://pastebin.com/C8JYHddQ
Here you go 👍 

(Did not work to upload the file here cuase of error of supporting file. Tried docx, zip.

**Comment by BobyTS** [comment]
Thank you @Iluminatos 
Do you use the latest version of Chocolatey? I invite you to use the latest release or clone the binaries branch.
https://github.com/sant0ro/chocolatey/releases

**Comment by Iluminatos** [comment]
Yes i do.

**Comment by Iluminatos** [comment]
The BETA version. My /photo page worked but stopped randomly, and the images dosent show.

**Comment by Iluminatos** [comment]
i could provide you Linux details, you could check it.

**Comment by BobyTS** [comment]
I do not see the error you encounter in **lumen.log**
Do you use PHP7?

**Comment by Iluminatos** [comment]
Yes i do :)

**Comment by BobyTS** [comment]
Hmm, have you checked `camera_web` table in your database ?

**Comment by Iluminatos** [comment]
Yes there is two images registerd. But the /community/photos page does not work o.O

**Comment by Iluminatos** [comment]
My page works now when i deleted everything in camera_web in db.
Why does not the pictures show tho?

**Comment by BobyTS** [comment]
@Iluminatos Problem comes from camera host, ssl is invalid

**Comment by Iluminatos** [comment]
And how do i fix this?

**Comment by Iluminatos** [comment]
And when logging in to my hotel i get to choose my Style & choose room for the first time.
But when i restart the server (:shutdown) and reload the client i come back to choose room & style then when im in the client i have 2 beginner rooms and so on. @BobyTS

**Comment by BobyTS** [comment]
Strange, this problem is solved on the latest version of Chocolatey.
I will check again.

Regarding the photos, you must setup a "proxy" to display images from the domain "http://arcturus.wf"

**Comment by Iluminatos** [comment]
I do have the latest version. Check out: 158.69.130.188

Oh ok.

**Comment by sant0ro** [comment]
@Iluminatos this isn't the latest Chocolatey version.

**Comment by BobyTS** [comment]
I confirm that you are not using the latest version of Chocolatey
For the proper functioning of Chocolatey,  I also recommend that you configure an SSL certificate on your domain.

**Comment by Iluminatos** [comment]
What do i replace? Do i need to reinstall all?

**Comment by BobyTS** [comment]
Yes, it will be easier for you to reinstall everything.

Try to understand how a git works, you can retrieve updates without difficulty from the binaries branch

**Comment by Iluminatos** [comment]
Thanks @BobyTS

**Comment by Iluminatos** [comment]
I updated my **CMS** now, but i **cannot register**, this error:
https://gyazo.com/47b5545dd8cde89ba2307f687cfcb11d

**Comment by Iluminatos** [comment]
I updated my **CMS** now, but i **cannot register,** getting this error:
https://gyazo.com/47b5545dd8cde89ba2307f687cfcb11d
@BobyTS @sant0ro

**Comment by sant0ro** [comment]
@Iluminatos we're busy. Please wait.

**Comment by Iluminatos** [comment]
@sant0ro I'll wait aslong as you will help me :) Cannot figure this out. The site and secret key is correct.

**Comment by BobyTS** [comment]
@Illuminos Chocolatey SQL table is different for account management. Have you reinstalled the Chocolatey SQL tables?

**Comment by Iluminatos** [comment]
Is there new structure on the new verision? I have the one provided on the verision i had before.

IF so, please attatch That SQL. :)

Thanks /illuminatos

**Comment by Iluminatos** [comment]
The **Arcturus.sql** inside the database folder does not contain any **"chocolatey" tables.**
Please provide then one i should be using, Many thanks.

**Comment by BobyTS** [comment]
Follow the step to configure the database.
Remove `migrations` table and `chocolatey_*` tables before running this command.
https://github.com/sant0ro/chocolatey/wiki/Installing-Chocolatey#configuring-database

**Comment by Iluminatos** [comment]
Will do this thanks. @BobyTS 
Where do i change the "PLAYING HABBO" Where is that file located?

**Thanks, Iluminatos.**

**Comment by sant0ro** [comment]
@Iluminatos from your running version to the new one multiple changes happened on the database structure.

Anyways, you're referring from the _menu_? "PLAYING HABBO"? You can change it on `/resources/views/habbo-web-10ln/en.json`

**Comment by Iluminatos** [comment]
Thanks for this information @sant0ro. Then it makes sense why it wouldnt work to **register.** 

No not the menu, the actuall information inside the **"PLAYING HABBO"**

How do i setup the "proxy" for the **community/photos**
Is it difficult?

**Thanks for the support.**

**Comment by sant0ro** [comment]
I don't know, never tested.

Playing Habbo Content is on `/resources/views/habbo-web-pages/``
Playing Habbo Texts is on `/resources/langs/`

Just search it.

**Comment by Iluminatos** [comment]
Alright, so there is no tutorial or some sort of information on how to setup photos?

**Comment by sant0ro** [comment]
Setup photos is an Arcturus tutorial. And it's easy.

Just need configurate the `config.ini` from Arcturus and put your username in Chocolatey `chocolatey.php` configuration.

Nothing more is required. Remember that from older versions, Chocolatey it's only now compatible with Arcturus 1.4.0

**Comment by Iluminatos** [comment]
Yes not to setup the photos itself. The actuall page "community/page"

So it should work if i have an activaited camera, upload to web?
Becuase on the older version there was an "broken image icon"

**Comment by Iluminatos** [comment]
Yes not to setup the photos itself. The actuall page **"community/page"**

So it should work if i have an activaited camera, upload to **web?**
Becuase on the older version there was an **"broken image icon"**

**Comment by Iluminatos** [comment]
Yes not to setup the photos itself. The actuall page **"community/page"**

So it should work if i have an activaited camera, upload to **web?**
Becuase on the older version there was an **"broken image icon"**
@sant0ro @BobyTS

**Comment by Iluminatos** [comment]
# **Found a bug!!**
When registrating the email can be changed due to the Users table (length).
I registerd with: official-ashez@hotmail.com and in the database it was changed to: official-ashez@hotmail.co

**This is a must fix.**

**Comment by sant0ro** [comment]
This isn't a bug. If you change the email on the database.

Because **you** changed it on the Database.

**Comment by sant0ro** [comment]
Only will show on the web if you click **publish to habboweb**

**Comment by Iluminatos** [comment]
Have not touched that user on the database o.o Will try again.

Here is a gif of the habboweb problem: 
https://gyazo.com/88131d5ce76f9fa3c5ca03aa27d2d7a3

The image is working on the database tho, the link works fine and it sends me to the image itself.

**Comment by Iluminatos** [comment]
Where do i change these things btw?

**BETA RELEASE**
Thanks for using Chocolatey. You’re using a BETA release of Chocolatey Content Management System. If you’re experiencing any bugs, you should report on our GitHub.

And..

Text inside /game when changing style, choosing name for the first time, Where is these texts located?

**Comment by sant0ro** [comment]
This thing will not be removable on BETA releases. Also the current version of Chocolatey will be added on it.

Only on definitive release we will remove it. It's a reminder to clarify that this a fucking **beta** release.

**Comment by Iluminatos** [comment]
**Great, thanks.**

Just changed my config IP to my domain in chocolatey.php config and now my emulator wont start ?

**Comment by Iluminatos** [comment]
_**Image:**_ https://gyazo.com/ef500dd79c4b4274d9b6fe412cc954cb

**Comment by sant0ro** [comment]
Changing on the CMS has nothing related on the Emulator. You cannot put a domain on the `config.ini` of the emulator. But you can do it on Chocolatey.

Anyways the error isn't related to the IP Address
![image](https://cloud.githubusercontent.com/assets/12037269/25451633/39ec191e-2a99-11e7-8547-94475a1ff37a.png)
If you see, it's a MySQL setting.

**Comment by Iluminatos** [comment]
OK, im guessing i have to add to the maximum packets size? Do you know how?

**Comment by sant0ro** [comment]
Does you fixed it?

**Comment by Iluminatos** [comment]
@sant0ro I did fix this issue. 

Last question of mine:
How do i change the amount of credits, duckets you start with?

**Comment by Iluminatos** [comment]
@sant0ro @BobyTS

**Comment by Iluminatos** [comment]
**@sant0ro I did fix this issue.**

**Last questions of mine:**
How do i change the amount of **credits, duckets** you start with?
What is the site **"/messaging"** for?
Where is the arcturus photo link configuration **(gonna setup a image proxy**)

**Comment by Iluminatos** [comment]
@sant0ro

**Comment by sant0ro** [comment]
The amount of starting credits, duckets I don't know where to change. Probably on database.
/messaging isn't anymore used and will be removed. Was for non-readed offline console messages.
Arcturus proxy? This doesn't exists...

**Comment by Iluminatos** [comment]
Thanks. 
Oh alright. Will there be any staff page?

"Strange, this problem is solved on the latest version of Chocolatey.
I will check again.

Regarding the photos, you must setup a "proxy" to display images from the domain "http://arcturus.wf"" **by Boby**

**Comment by BobyTS** [comment]
This was only a suggestion, try setup a php script to display arcturus images.
Or force use the http domain from arcturus.wf

**Comment by Iluminatos** [comment]
How do i force the domain?

**Comment by Iluminatos** [comment]
@BobyTS

**Comment by Iluminatos** [comment]
@BobyTS @sant0ro

**Comment by sant0ro** [comment]
@Iluminatos this is not a chatbox.

Idk why you're trying to do proxy with Arcturus camera, mate. It's totally unncessary.

This is a support for Chocolatey, not for Arcturus. Arcturus Issues, go to his repository or Habbo Help Section.

We also have guides in our wiki.

Camera is really easy to configure. Check also F.A.Q. Section on Arcturus Release thread.

Closing this, since the "Choose Style Room Issue" already fixed and this has nothing to do with it.

Sorry for being rude @Iluminatos but please, try search a little more :)
