### ISSUE TITLE
Captcha does not work for me

### ISSUE THREAD

**Issue by jensvos** [sant0ro/chocolatey#220]
I got a key from Google for the reCaptcha. When I go to register and want to make an avatar, it still says: "You need to verify that you're not a robot". I also even tried to get new reCaptcha keys and tried to use the secret key and the public one. It still does not work. How can I fix this or even disable the captcha? It is driving me crazy. 

Hotel link: http://hypnohotel.nl

**Comment by sant0ro** [comment]
Hi @jensvos!

Thanks for reporting an Issue to the **Chocolatey Repository**.

We're glad that you're using our software. I need to remember that **this** message was generated automatically.

In order to **gracefully** report your Issue, please we recommend the followance of those requirements:

Here's what to do: if you need help:

* Inform a complete message of your problem, and what's happening.
* Attach your **lumen.log** if it exists.
* Attach images of the reported bugs/glitches.
* Attach also Information about Operational System, Web Server, PHP Versiom, and other infos.
* Explain what you tried and how tried.

Recommendations About your recently opened Issue?
--------------------------------

We really recommend using [Lightshot](https://app.prntscr.com/pt-br/download.html) to take your screenshot. It allows marks, annotations and more.

If you bug it's about a feature from **Chocolatey** or glitch, we **trully** recommend taking a **HAR File**. You can attach a [HAR File following this procedure](https://support.cloudflare.com/hc/en-us/articles/203118044-How-do-I-generate-a-HAR-file-).

A **HAR** file it's a complete log of the network requests of a specific page.

Also we recommend specify some Informations about your **OS** like.:

* Operational System
* Which Web Server are you using (like XAMPP)
* Which version of Web Server Using (eg.: 1.7.3)
* Which version of php & mysql & apache using. (Specify if is possible)
* How much RAM does you have?

Are you creating a Feature Request?
------------------------------

About Feature requests, we recommend you specify completely about what your **Feature Request** is. Tag the type of change that you want to be added.

Changes need to be specified, and you need specify why and what you want to be changed/added.

Be creatively and try explain in the best manner as possible.

Tag the Issue on the Title
-------------------------------

Tagging your Issue will be the best thing you can do for us. We separate issues by tags, and we can work more quickly by knowing from what is the Issue related.

**Those are the available tags:**

* Security
* Angular
* Feature Request
* Server Error
* HabboWEB Glitch
* Translation Mistake
* CSS Mistake/Glitch
* Feature not Working
* Help Wanted
* Can't Install
* Urgent Issue
* Game Bug
* Migration Bug
* Upgrading Bug

**Remember to tag on the title of the Issue [_Issue Type_]**

I updated my Issue.. And now?
---------------------------

You wait.

We have **ful-jobs** and a **life**, we will receive updates by e-mail and soon as possible update your **Issue** by tagging it correctly, assigning to our team and **obviously** answering it.

Then we will support you and help you in what we can.

Also if you Issue it's out of the **params** we will not answer it, or answer it **asking to you fix and correct the main message**

If you dom't know how to use GitHub correctly, check [this](https://guides.github.com/features/issues/) tutorial.

Further information
-------------------

* This **BOT** was originally created by @ajdlinux and @daxtens.
* Edited by @sant0ro for own purposes.
* Contributors of Chocolatey @BobyTS and @s150217754

**Comment by Iluminatos** [comment]
Please record your issue when you try to register.
**Advice: Try Gyazo GIF.**

Best Regards.

**Comment by sant0ro** [comment]
Hi @jensvos does you already tried to run `php artisan migrate` command?

**Comment by jensvos** [comment]
Yes, I have done the php artisan migrate command. It imported 18 tables into the database.

**Comment by jensvos** [comment]
And this is what it shows: https://gyazo.com/2343e69d5d7e06c59269598cc24605b0

**Comment by sant0ro** [comment]
Does actually you generated the key and included the domain?

**Comment by jensvos** [comment]
Yes, of course. http://prntscr.com/f3s6hw I even tried to turn off CloudFlare, but it did not work. But... if I check the F12 console, I sometimes see 500 Internal Error and have error: MethodNotAllowedHttpException in RoutesRequests.php line 596. I am using the latest version of XAMPP and have Chocolately version 3000D installed. So...

**Comment by jensvos** [comment]
Check this: http://prntscr.com/f3s87t

**Comment by sant0ro** [comment]
Okay, isn't a Captcha problem. Clear the follow file `storages/logs/lumen.log` and try register again. And send me the file after trying to register again.

You can attach it here.

**Comment by jensvos** [comment]
[lumen.txt](https://github.com/sant0ro/chocolatey/files/976836/lumen.txt)

**Comment by jensvos** [comment]
After clearing the lumen.log, register still does not work. I am clueless right now.

**Comment by sant0ro** [comment]
It seems that you forgot to import Arcturus Database.

The error is: "Base table or view not found: 1146 Table 'arcturus.bans' doesn't exist in C:"

**Comment by jensvos** [comment]
I actually have imported the database. That is not the problem. 
![image](https://cloud.githubusercontent.com/assets/27585688/25784417/cecb6018-336c-11e7-8cde-17c50464047e.png)

**Comment by sant0ro** [comment]
Your database is incomplete.

**Comment by s150217754** [comment]
To re-migrate your Chocolatey tables, drop all tables starting with ```chocolatey_``` and the ```migrations``` table and re-run the migration command ```php artisan migrate```.

**Comment by sant0ro** [comment]
Yeah, but @s150217754 also non chocolatey tables are incomplete. Check that the `bans` tables as an example, doesn't exists.

**Comment by jensvos** [comment]
It is annoying, because I have tried dozens of databases. I tried the official one from Wesley's bitbucket for Arcturus, I tried yours in the 'database' folder in the CMS root and I even tried the Arcturus 1.6.0 Emulator folder SQL. 👎

**Comment by s150217754** [comment]
First, as @sant0ro have mentioned, your Arcturus base SQL file is incomplete. Drop your whole database and use a third-party SQL application like HeidiSQL or Navicat to run Arcturus' base SQL file.

Next, you should **not** run the files in Chocolatey's database folder direcrly. These files are handled and used by the Artisan console. Read our [wiki](https://github.com/sant0ro/chocolatey/wiki/Installing-Chocolatey) for more information on how to migrate those SQL into your database via the `php artisan migrate` command.

We do not provide warranty or support if you try to install Chocolatey using other means other than the Artisan console.
