### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by Draxprodd** [sant0ro/chocolatey#257]
Hello,

I have an error when I go to the website...
I do not understand why, I took the latest version of the CMS (branch master)

Warning: require_once(C:\xampp\htdocs\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\bootstrap\app.php on line 3

Fatal error: require_once(): Failed opening required 'C:\xampp\htdocs\bootstrap/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\bootstrap\app.php on line 3

Thanks

**Comment by thedevilsden** [comment]
First of all, what version of **XAMPP** are you currently on?
Second, did you follow the Installation Process **as written in the wiki**?
If you have problems with **composer**, try switching to the ZIP binaries. Then configure your .env file.
Do a fresh install of XAMPP in case, then reboot your machine. Remember, your **wwwroot** (_although not supported yet_) or **htdocs folder** should look like this:
![index](https://user-images.githubusercontent.com/29677996/27530537-6c26862c-5a59-11e7-8465-8d64a18b8334.png)
Do not mind the _swf_ folder for now, it's the one I'm using on my hotel currently.

**Comment by sant0ro** [comment]
@Draxprodd does you downloaded the binary? Available on "Releases" page?

<pre>
Warning: require_once(C:\xampp\htdocs\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\bootstrap\app.php on line 3
</pre>

This generally happens because the `vendored` files doesn't exists. Only the binaries comes within it.

Recommend download it.

**Comment by sant0ro** [comment]
Closed because of lack of updates.
