### ISSUE TITLE
Little 76% disconnect bug

### ISSUE THREAD

**Issue by ElroyNL** [sant0ro/chocolatey#260]
Hello,

I don't know if other users already experience this bug, but most of the **first** times after I logged in at the hotel, I will be disconnected at 76% of the client loading. When I click the Reload button, it will load the hotel... The most of my users experience this error, it is anying everytime when you log in, two times loading the hotel.

Hoping for an solution.

Groetjes (Dutch for greetings)

**Comment by sant0ro** [comment]
Maybe this being a Ticket generation bug. But this didn't happened with me.

I will try to run Chocolatey again and see if this happens.

**Comment by sant0ro** [comment]
@ElroyNL I can't replicate this bug. Are you sure that this bug continues?

**Comment by TheOmanNorge** [comment]
I took my sweet time to record. 
https://www.youtube.com/watch?v=5un4tDxs4R0

After you login and wait a few seconds and then click on Hotel.
It first goes up to 76% and then reloads. 

I might be wrong here since he said "Reload" button as that never appairs for me but
instead just reloads. But if this is the "error" then this has been for a long time. 

I've never seen that as a big issue for me or a problem.
But of course if this is the problem and if this can be fixed, then that's all good in itself. 👍

**Comment by sant0ro** [comment]
I never saw this Issue happening with me. That's really weird. But not a really big problem.

@TheOmanNorge NUX rooms are working with you?

**Comment by TheOmanNorge** [comment]
Yes they are. Just deleted all of the furni so my dog could run around. 
Yes NUX rooms works perfect for me. 👍

**Comment by sant0ro** [comment]
Closing.
