### ISSUE TITLE
chocolatey suggestions

### ISSUE THREAD

**Issue by odrik** [sant0ro/chocolatey#292]
hello.

Is it possible to simplify the installation of chocolatley via a simple web page? 
Also an interface to update the version of our chocolatley directly from a web page would also be cool.
And finally, a demo link of chocolatley updated to the latest version would be cool!
+ add the number of badges on the habbo homepage.

Ps: I'm looking for Espresso or view screens if not yet available? Thanks for the great job you do

**Comment by sant0ro** [comment]
"add the number of badges on the habbo homepage." Is this a feature that exists on Original Habbo?

Espresso isn't coded yet. (And maybe will not comer really soon, because of personal problems).

I don't have time for now to code a web installer, m8.

Update Chocolatey to latest version? It's easy just download the zip and replace with yours. Updating will do the same, probably replacing all your "edited" files. This is complex and not easy.

Closing Issue, since I don't have time for both, Sorry.
