### ISSUE TITLE
Email doesn't work

### ISSUE THREAD

**Issue by PunchoDelta** [sant0ro/chocolatey#295]
Hello,

I configured mail.php with gmail and it does not work, no error in lumen, i understand why it does not work
Can you help me?

**Comment by TheOmanNorge** [comment]
Post your mail.php file.
So i can see what you have done wrong. 

Leave out password.

**Comment by PunchoDelta** [comment]
That's my mail.php file
https://pastebin.com/uVX0rbQm

**Comment by sant0ro** [comment]
E-mail works, you need configure it.

Proof that works #286 

Just configure it correctly.

Read those:
https://support.google.com/accounts/answer/6010255?hl=pt-BR
https://support.google.com/a/answer/176600?hl=pt-BR

**Comment by TheOmanNorge** [comment]
Try using secure connection. 

My settings. 

 'driver' => env('MAIL_DRIVER', 'smtp'),
 'host' => env('MAIL_HOST', 'smtp.gmail.com'),

 'address' => 'chocolateycms@gmail.com',
 'name'    => 'Nightbox Hotel',

 'username' => env('MAIL_USERNAME', 'chocolateycms@gmail.com'),
 'password' => env('MAIL_PASSWORD', 'PasswordMustBeInHere'),
 'port' => env('MAIL_PORT', 465),
 'encryption' => env('MAIL_ENCRYPTION', 'SSL'),

It didnt work for my old gmail account, I told me in the log file it was the wrong password.
Not sure If it was because of extra layer of security when logging in. 

So i created a new gmail account, and works fine.

**Comment by sant0ro** [comment]
Just complementing the @TheOmanNorge answer.

You also can make it work with TLS. (TLS it's more recommended than SSL),

Also @TheOmanNorge may didn't worked in your old gmail account because of security policies or Two Factor Authentication. Or Less Secure Apps wasn't enabled.

**Comment by TheOmanNorge** [comment]
Yes might have been the case for me on the old account. 😸

**Comment by PunchoDelta** [comment]
Ok nice, it's fixed

**Comment by PunchoDelta** [comment]
Thank you

**Comment by TheOmanNorge** [comment]
Good! 👍
