### ISSUE TITLE
Profile page error

### ISSUE THREAD

**Issue by killerrichard** [sant0ro/chocolatey#322]
look at the end of the profile page 

" A REJOINT HABBO LE 2017-04-01T20:47:16.-25200-25200-25200-25200+-25200-25200-25200-25200 "

**Comment by TheOmanNorge** [comment]
Yes check your timezone in php.ini file, try to adjust or remove it. Might fix your problem.

Looks like many have this problem after this last update, honestly not sure if Timezone is the real problem and fix, but fixed my problem aleast when I updated to the same timezone the server had.

**Comment by sant0ro** [comment]
This isn't a bug of the latest version. I didn't changed anything related on it. I never saw this kind of date format. It's really curious. That probably happens because your servers local date format isn't compatible with the supported by Chocolatey.

That doesn't mean that your GMT isn't supported. But the time it's provided in a format that Chocolatey cannot recover it contents.

Fully recommend see this Issue: #319 .

Closing since the solution for this kind of issue was already released.

If you have any further question, feel free to reopen this issue 😄

**Comment by PunchoDelta** [comment]
strange, has this been added recently?
