### ISSUE TITLE
"Https" and localhost problem.

### ISSUE THREAD

**Issue by Anthologique** [sant0ro/chocolatey#88]
camera picture dont load with your fucking "https" by default link.
Images dont load for me, on localhost, when i change your "https" link on "http" on my camera_web table,
![2](https://cloud.githubusercontent.com/assets/6734589/23948562/dd1ef566-0983-11e7-902d-713fc32a86ee.png)
 its works.
Look screenshot please.

**Comment by s150217754** [comment]
First, there's no need for you to be rude.

As far as I know, there's no problem with Chocolatey since the "HTTPS by default" only applies to the Room Thumbnail and Full Room Screenshot.

As for User Photos, Chocolatey fetches the Image URL directly from your 'camera_web' table.

This value is generated by the emulator using your configuration. So, either there's a problem with the Emulator or your configuration is wrong.

**Comment by sant0ro** [comment]
Exactly @Anthologique, the link is generated by Arcturus. I said to Wesley remove the http:// thing.

Because HabboWEB add it's automatically.

**Comment by Anthologique** [comment]
I am sorry for my bad langage.
Okay, the problem is Arcturus Emulator and no your CMS.
